### ISSUE TITLE
Question -  quick access to most commonly used keys especially for programming

### ISSUE THREAD

**Issue by flight505** [MayTD/DoMo-Macro-Pad#8]
Hi May, sorry for creating an "issue" but Git doesn't allow direct messages so it was the only way to ask you a question. 
Really cool you made this, I love the idea of having an OLED to play around with some code on. Well, the reason I am writing is that I recently bought a macro board with a large rotary encoder. I just use it for media control and I have a layer set up for adobe illustrator. 
Now I was looking for some idea on how to efficiently use it for programming and VScode and then stumbled across your git. I spent some time setting up a layer on my 60% keyboard dedicated to VScode and writing some macros and scripts, the idea was to keep my hands resting on the keyboard while coding/writing and avoid moving to the mouse. 
But, I thought there could be some really smart things that could take advantage of the rotary encoder while programming but I haven't found any - if you have discovered some great workflows for programming then please share 
Thanks and merry x-mas 🎄

**Comment by MayTD** [comment]
@flight505 I use the rotary encoder for volume control but a few suggestions for avoiding the mouse is to use the encoder for scrolling, tab control, or undo/redo. Hope this gives you some ideas!
